python textcnn_main.py --pretrained_dir="../data/cnews/final_data/wiki_word/" --pretrained_name="wiki.word.embedding.pkl" --data_dir="../data/cnews/final_data/wiki_word/" --log_dir="../logs/" --output_dir="../checkpoints/" --num_tags=10 --seed=123 --gpu_ids="0" --max_seq_len=32 --lr=3e-5 --train_batch_size=128 --train_epochs=10 --eval_batch_size=128 --dropout=0.3 --use_pretrained --vocab_size=352217 --embedding_size=300 --num_filters=256 --filter_sizes="2,3,4"

python textrnn_main.py --pretrained_dir="../data/cnews/final_data/wiki_word/" --pretrained_name="wiki.word.embedding.pkl" --data_dir="../data/cnews/final_data/wiki_word/" --log_dir="../logs/" --output_dir="../checkpoints/" --num_tags=10 --seed=123 --gpu_ids="0" --max_seq_len=32 --lr=3e-5 --train_batch_size=128 --train_epochs=10 --eval_batch_size=128 --dropout=0.3 --use_pretrained --vocab_size=352217 --hidden_size=128 --num_layers=2

python textrnn_bc_main.py --pretrained_dir="../data/cnews/final_data/wiki_word/" --pretrained_name="wiki.word.embedding.pkl" --data_dir="../data/cnews/final_data/wiki_word/" --log_dir="../logs/" --output_dir="../checkpoints/" --num_tags=10 --seed=123 --gpu_ids="0" --max_seq_len=32 --lr=3e-5 --train_batch_size=128 --train_epochs=10 --eval_batch_size=128 --dropout=0.3 --use_pretrained --vocab_size=352217 --hidden_size=128 --num_layers=2

python textrcnn_main.py --pretrained_dir="../data/cnews/final_data/wiki_word/" --pretrained_name="wiki.word.embedding.pkl" --data_dir="../data/cnews/final_data/wiki_word/" --log_dir="../logs/" --output_dir="../checkpoints/" --num_tags=10 --seed=123 --gpu_ids="0" --max_seq_len=32 --lr=3e-5 --train_batch_size=128 --train_epochs=10 --eval_batch_size=128 --dropout=0.3 --use_pretrained --vocab_size=352217 --hidden_size=256 --num_layers=1

python fasttext_main.py --pretrained_dir="../data/cnews/final_data/wiki_word/" --pretrained_name="wiki.word.embedding.pkl" --data_dir="../data/cnews/final_data/wiki_word/" --log_dir="../logs/" --output_dir="../checkpoints/" --num_tags=10 --seed=123 --gpu_ids="0" --max_seq_len=32 --lr=3e-5 --train_batch_size=128 --train_epochs=10 --eval_batch_size=128 --dropout=0.3 --use_pretrained --vocab_size=352217 --hidden_size=256

python dpcnn_main.py --pretrained_dir="../data/cnews/final_data/wiki_word/" --pretrained_name="wiki.word.embedding.pkl" --data_dir="../data/cnews/final_data/wiki_word/" --log_dir="../logs/" --output_dir="../checkpoints/" --num_tags=10 --seed=123 --gpu_ids="0" --max_seq_len=32 --lr=3e-5 --train_batch_size=128 --train_epochs=10 --eval_batch_size=128 --dropout=0.3 --use_pretrained --vocab_size=352217 --num_filters=256

python textrnn_att_main.py --pretrained_dir="../data/cnews/final_data/wiki_word/" --pretrained_name="wiki.word.embedding.pkl" --data_dir="../data/cnews/final_data/wiki_word/" --log_dir="../logs/" --output_dir="../checkpoints/" --num_tags=10 --seed=123 --gpu_ids="0" --max_seq_len=32 --lr=3e-5 --train_batch_size=128 --train_epochs=10 --eval_batch_size=128 --dropout=0.3 --use_pretrained --vocab_size=352217 --hidden_size=128 --hidden_size2=64

python transformer_main.py --pretrained_dir="../data/cnews/final_data/wiki_word/" --pretrained_name="wiki.word.embedding.pkl" --data_dir="../data/cnews/final_data/wiki_word/" --log_dir="../logs/" --output_dir="../checkpoints/" --num_tags=10 --seed=123 --gpu_ids="0" --max_seq_len=32 --lr=3e-5 --train_batch_size=128 --train_epochs=10 --eval_batch_size=128 --dropout=0.3 --use_pretrained --vocab_size=352217 --hidden_size=1024 --last_hidden_size=512 --dim_model=300 --num_head=5 --num_encoder=2

